### ISSUE TITLE
How to fetch csv files pointing from git-lfs pointers

### ISSUE THREAD

**Issue by eya-abid** [benedekrozemberczki/datasets#10]
So I am trying to download the Facebook Large dataset. But the zip file has 2 CSV files that only contain git-lfs pointers:
![image](https://user-images.githubusercontent.com/52136917/204789126-f5eb2f01-fc6c-4ed6-9b97-5a4604a403ff.png)

Any idea how to retrieve the dataset from these git-lfs pointers?

Thanks!

**Comment by benedekrozemberczki** [comment]
Could you be more specific which links are problematic?

**Comment by luisfredgs** [comment]
Same problem here. The zip file for Deezer Europe has 2 CSV files that only contain git-lfs pointers.  How to download the dataset from git-lfs pointers you placed in CSVs?
