### ISSUE TITLE
Could you provide an example of how to download the datasets?

### ISSUE THREAD

**Issue by luisfredgs** [benedekrozemberczki/datasets#11]
Could you provide an example of how to download the datasets?

The zip file for Deezer Europe Dataset has 2 CSV files that only contain git-lfs pointers. How to download the dataset from git-lfs pointers you placed in CSVs?

![image](https://user-images.githubusercontent.com/852491/225171800-dc9f0260-e02e-478e-9078-995bf76449f7.png)

**Comment by benedekrozemberczki** [comment]
Updated the link.
