### ISSUE TITLE
Features in Github Web-ML not of same length

### ISSUE THREAD

**Issue by yifanyang96** [benedekrozemberczki/datasets#3]
Hi,

The features in `git_web_ml/git_feature.json` are not of same length. Should the shorter ones be padded with 0s to the end? Or is there a feature matrix of shape (node_num, feature_num) or a sparse mat with node_id, feature_id and value?

Thank you!

**Comment by benedekrozemberczki** [comment]
The keys are nodes and the values are list with feature indices. It is a sparse binary feature matrix. EIn other words, essentially row indices are keys, the list values are column indices.
