### ISSUE TITLE
Twitch Social Network dataset: Target

### ISSUE THREAD

**Issue by tonygracious** [benedekrozemberczki/datasets#5]
The target files in twitch social network contain the following columns id,days,mature,views,partner,new_id. Could you please provide some information regarding these values, and also, can you please point which column is used for the node classification task ?

**Comment by benedekrozemberczki** [comment]
Have you seen my paper on this topic?

**Comment by tonygracious** [comment]
I have seen the paper Multi-Scale Attributed Node Embedding. It says this   "The associated task is binary classification of whether a streamer uses explicit language."  about the target variable. My guess is that 'mature' column is the target variable.  But, I do not understand other columns. Is it possible to share some descriptions of other columns?  Can they be used in any supervised task?

**Comment by benedekrozemberczki** [comment]
There is also this paper:

https://arxiv.org/pdf/2101.03091.pdf

This gives a better explanation of what we did on a larger dataset. Hope it
helps.

**Comment by tonygracious** [comment]
Thanks
