### ISSUE TITLE
MUSAE-Twitch dataset features

### ISSUE THREAD

**Issue by karuna-bhaila** [benedekrozemberczki/datasets#7]
Hello, 
Thank you for your work!

For the features.json file in the twitch dataset, is there a reference for what the feature indices in the values list specifically represent? For e.g: it's mentioned the features are extracted from games played. Do some of the values in the list represent ids of the games played by that user? Is there a way to get information on what each value corresponds to?

**Comment by benedekrozemberczki** [comment]
Read the paper.
