### ISSUE TITLE
Question about the LastfmAsia and DeezerEurope datasets

### ISSUE THREAD

**Issue by virginie-do** [benedekrozemberczki/datasets#8]
I have a question about the LastfmAsia and DeezerEurope datasets of your CIKM 2020 paper, which I found on SNAP. These datasets are provided with node features which are “extracted based on the artists liked by the users”. Does this mean that each number in the vector associated to each node corresponds to the id of an artist that the user node liked? Or is the vector a more abstract embedding? I am referring to the file `lastfm_asia_features.json` and `deezer_europe_features.json`.

Thanks in advance!

**Comment by benedekrozemberczki** [comment]
Yes!
